name: 'Build, test & publish'
on:
  pull_request:
  push:

jobs:
  all: # make sure build/ci work properly
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: |
          npm install
      - run: |
          npm run all
      - name: Test action
        uses: ./
        if: github.event_name == 'push'
        with:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          domain: action-test.onramper.dev
          publish_dir: ./images
      - name: Publish artifacts
        if: github.event_name == 'push' && github.ref == 'refs/heads/master'
        run: |
          mv gitignore-build .gitignore
          git config user.email "$GITHUB_ACTOR@users.noreply.github.com"
          git config user.name "$GITHUB_ACTOR"
          git add .
          git commit -m "Add build artifacts" > /dev/null
          git push origin HEAD:v1 -f